import js from '@eslint/js';
import globals from 'globals';

export default [
    js.configs.recommended,
    {
        // Browser extension files
        files: ['extension/**/*.js'],
        languageOptions: {
            ecmaVersion: 2025,
            sourceType: 'script',
            globals: {
                ...globals.browser,
                ...globals.webextensions,
                chrome: 'readonly',
                STANDARD_GATT_SERVICES: 'writable',
                STANDARD_GATT_CHARACTERISTICS: 'writable',
                STANDARD_GATT_DESCRIPTORS: 'writable',
                BluetoothUUID: 'writable',
            },
        },
        rules: {
            'indent': ['error', 4],
            'array-bracket-spacing': ['error', 'never'],
            'block-spacing': ['error', 'never'],
            'brace-style': 'error',
            'camelcase': ['error', { properties: 'never' }],
            'comma-dangle': ['error', 'always-multiline'],
            'comma-spacing': 'error',
            'comma-style': 'error',
            'computed-property-spacing': 'error',
            'consistent-this': 'error',
            'eol-last': 'error',
            'func-call-spacing': 'error',
            'key-spacing': 'error',
            'keyword-spacing': 'error',
            'max-depth': ['error', 7],
            'max-len': ['error', {
                'code': 120,
                'ignoreUrls': true,
                'ignoreTemplateLiterals': true,
            }],
            'max-nested-callbacks': ['error', 4],
            'max-params': ['error', 10],
            'new-cap': 'error',
            'no-array-constructor': 'error',
            'no-multiple-empty-lines': ['error', { max: 2 }],
            'no-new-object': 'error',
            'no-tabs': 'error',
            'no-trailing-spaces': 'error',
            'object-curly-spacing': ['error', 'always'],
            'one-var': ['error', {
                var: 'never',
                let: 'never',
                const: 'never',
            }],
            'padded-blocks': ['error', 'never'],
            'quote-props': ['error', 'consistent'],
            'quotes': ['error', 'single', { allowTemplateLiterals: true }],
            'semi': 'error',
            'semi-spacing': 'error',
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', {
                asyncArrow: 'always',
                anonymous: 'always',
                named: 'never',
            }],
            'spaced-comment': ['error', 'always'],
            'switch-colon-spacing': 'error',
        },
    },
    {
        // Test files with Jest and Node.js
        files: ['tests/**/*.js', 'wallaby.js'],
        languageOptions: {
            ecmaVersion: 2025,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
                ...globals.jest,
            },
        },
        rules: {
            'indent': ['error', 4],
            'array-bracket-spacing': ['error', 'never'],
            'block-spacing': ['error', 'never'],
            'brace-style': 'error',
            'camelcase': ['error', { properties: 'never' }],
            'comma-dangle': ['error', 'always-multiline'],
            'comma-spacing': 'error',
            'comma-style': 'error',
            'computed-property-spacing': 'error',
            'consistent-this': 'error',
            'eol-last': 'error',
            'func-call-spacing': 'error',
            'key-spacing': 'error',
            'keyword-spacing': 'error',
            'max-depth': ['error', 7],
            'max-len': ['error', {
                'code': 120,
                'ignoreUrls': true,
                'ignoreTemplateLiterals': true,
            }],
            'max-nested-callbacks': ['error', 4],
            'max-params': ['error', 10],
            'new-cap': 'error',
            'no-array-constructor': 'error',
            'no-multiple-empty-lines': ['error', { max: 2 }],
            'no-new-object': 'error',
            'no-tabs': 'error',
            'no-trailing-spaces': 'error',
            'object-curly-spacing': ['error', 'always'],
            'one-var': ['error', {
                var: 'never',
                let: 'never',
                const: 'never',
            }],
            'padded-blocks': ['error', 'never'],
            'quote-props': ['error', 'consistent'],
            'quotes': ['error', 'single', { allowTemplateLiterals: true }],
            'semi': 'error',
            'semi-spacing': 'error',
            'space-before-blocks': 'error',
            'space-before-function-paren': ['error', {
                asyncArrow: 'always',
                anonymous: 'always',
                named: 'never',
            }],
            'spaced-comment': ['error', 'always'],
            'switch-colon-spacing': 'error',
        },
    },
];
